#!/usr/bin/env python3
"""Generate lib/unicode_ranges.h from llama.cpp's own unicode-data.cpp.

The GLM-4 pre-tokenizer regex is written in terms of \\p{L} and \\p{N}, so
splitting text the way llama.cpp splits it needs the same idea of which code
points are letters and which are numbers. Deriving the table from llama.cpp's
`unicode_ranges_flags` rather than from Python's `unicodedata` makes that
identical *by construction*: the two would otherwise agree only as far as their
Unicode revisions happen to agree, and a disagreement would surface as a
handful of mis-tokenized code points somewhere in the tail of a script nobody
tests.

Only two of the eight categories are extracted, because only two appear in the
regex. Whitespace is a 25-entry set copied verbatim in the header.

    python lib/gen_unicode_ranges.py <llama.cpp>/src/unicode-data.cpp > lib/unicode_ranges.h
"""

import re
import sys

NUMBER = 0x0002
LETTER = 0x0004
MAX_CP = 0x110000


def parse(path):
    """-> list of (start, flags), ascending; each entry runs to the next start."""
    text = open(path, encoding="utf-8").read()
    body = text.split("unicode_ranges_flags = {", 1)[1].split("};", 1)[0]
    out = []
    for m in re.finditer(r"\{\s*(0x[0-9A-Fa-f]+)\s*,\s*(0x[0-9A-Fa-f]+)\s*\}", body):
        out.append((int(m.group(1), 16), int(m.group(2), 16)))
    if not out:
        raise SystemExit("no ranges parsed from %s" % path)
    return out


def ranges_with(entries, bit):
    """Merge the entries whose flags carry `bit` into [lo, hi] spans."""
    spans = []
    for i, (start, flags) in enumerate(entries):
        end = entries[i + 1][0] - 1 if i + 1 < len(entries) else MAX_CP - 1
        if flags & bit:
            if spans and spans[-1][1] + 1 == start:
                spans[-1][1] = end
            else:
                spans.append([start, end])
    return spans


def emit(name, spans, out):
    out.write("static const uint32_t %s[][2] = {\n" % name)
    for i in range(0, len(spans), 4):
        row = "".join("{0x%06X,0x%06X}," % (a, b) for a, b in spans[i:i + 4])
        out.write("    " + row + "\n")
    out.write("};\n\n")


def main():
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    entries = parse(sys.argv[1])
    letters = ranges_with(entries, LETTER)
    numbers = ranges_with(entries, NUMBER)

    o = sys.stdout
    o.write("#pragma once\n\n")
    o.write("// GENERATED by lib/gen_unicode_ranges.py from llama.cpp's\n"
            "// src/unicode-data.cpp - do not edit. Regenerate when the ggml/llama.cpp\n"
            "// pin moves, and re-run `python tokenizer_check.py` afterwards: this is\n"
            "// the table that decides where the pre-tokenizer splits, so a stale copy\n"
            "// shows up as tokenization that disagrees with llama.cpp on rare scripts\n"
            "// and nowhere else.\n//\n")
    o.write("// %d letter ranges, %d number ranges, covering \\p{L} and \\p{N} -\n"
            "// the only two categories the GLM-4 pre-tokenizer regex mentions.\n\n"
            % (len(letters), len(numbers)))
    o.write("#include <cstdint>\n\n")
    emit("NANO_UNICODE_LETTER", letters, o)
    emit("NANO_UNICODE_NUMBER", numbers, o)

    # Verbatim from unicode-data.cpp's unicode_set_whitespace.
    ws = [0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x20, 0x85, 0xA0, 0x1680,
          0x2000, 0x2001, 0x2002, 0x2003, 0x2004, 0x2005, 0x2006, 0x2007,
          0x2008, 0x2009, 0x200A, 0x2028, 0x2029, 0x202F, 0x205F, 0x3000]
    o.write("// unicode_set_whitespace, verbatim (ascending, binary-searchable)\n")
    o.write("static const uint32_t NANO_UNICODE_WHITESPACE[] = {\n")
    for i in range(0, len(ws), 8):
        o.write("    " + "".join("0x%06X," % c for c in ws[i:i + 8]) + "\n")
    o.write("};\n")


if __name__ == "__main__":
    main()
