#include <bits/stdc++.h>
using namespace std;

class Parser {
public:
    enum Context { BLOCK_IN, BLOCK_OUT, BLOCK_KEY, FLOW_IN, FLOW_OUT, FLOW_KEY };
    explicit Parser(std::u32string input) : s(std::move(input)) { rebuildLineStarts(); resetDoc(); }
    bool parseStream() {
        if (hasBadLeadingTabs()) return false;
        size_t p = 0;
        bool bareAllowed = true;
        while (true) {
            if (!consumeDocumentPrefix(p)) return false;
            if (p >= s.size()) return true;
            if (isDocumentEndAt(p)) { if (!consumeDocumentSuffix(p)) return false; bareAllowed = true; continue; }
            if (atLineStart(p) && peek(p) == U'%') { if (!bareAllowed) return false; resetDoc(); if (!parseDirectiveDocument(p)) return false; bareAllowed = false; }
            else if (isDirectivesEndAt(p)) { resetDoc(); if (!parseExplicitDocument(p, false)) return false; bareAllowed = false; }
            else { if (!bareAllowed) return false; resetDoc(); if (!parseBareDocument(p)) return false; bareAllowed = false; }
        }
    }
private:
    static constexpr char32_t BOM = 0xFEFF;
    std::u32string s; vector<size_t> lineStarts;
    struct DocState { unordered_set<std::u32string> anchors; unordered_map<std::u32string,std::u32string> tagHandles; unordered_set<std::u32string> explicitTagHandles; bool yamlDirectiveSeen=false; } doc;
    struct Snapshot { unordered_set<std::u32string> anchors; bool yamlDirectiveSeen; unordered_map<std::u32string,std::u32string> tagHandles; unordered_set<std::u32string> explicitTagHandles; };
    static std::u32string U(const char*z){std::u32string r; while(*z) r.push_back((unsigned char)*z++); return r;}
    void resetDoc(){doc.anchors.clear(); doc.tagHandles.clear(); doc.explicitTagHandles.clear(); doc.yamlDirectiveSeen=false; doc.tagHandles[U("!")]=U("!"); doc.tagHandles[U("!!")]=U("tag:yaml.org,2002:");}
    Snapshot save()const{return Snapshot{doc.anchors,doc.yamlDirectiveSeen,doc.tagHandles,doc.explicitTagHandles};}
    void restore(const Snapshot&sn){doc.anchors=sn.anchors; doc.yamlDirectiveSeen=sn.yamlDirectiveSeen; doc.tagHandles=sn.tagHandles; doc.explicitTagHandles=sn.explicitTagHandles;}
    void rebuildLineStarts(){lineStarts.clear(); lineStarts.push_back(0); for(size_t i=0;i<s.size();++i) if(s[i]==U'\n') lineStarts.push_back(i+1);} 
    bool eraseBOMAt(size_t&p){ if(p<s.size()&&s[p]==BOM&&atLineStart(p)){s.erase(s.begin()+(ptrdiff_t)p); rebuildLineStarts(); return true;} return false; }
    char32_t peek(size_t p,size_t off=0)const{size_t q=p+off; return q<s.size()?s[q]:0;}
    bool atLineStart(size_t p)const{return p==0||(p<=s.size()&&s[p-1]==U'\n');}
    size_t lineIndex(size_t p)const{auto it=upper_bound(lineStarts.begin(),lineStarts.end(),p); if(it==lineStarts.begin()) return 0; return (size_t)(it-lineStarts.begin()-1);} 
    bool sameLine(size_t a,size_t b)const{return lineIndex(a)==lineIndex(b);} int column(size_t p)const{return (int)(p-lineStarts[lineIndex(p)]);} size_t currentLineStart(size_t p)const{return lineStarts[lineIndex(p)];}
    size_t lineEnd(size_t p)const{while(p<s.size()&&s[p]!=U'\n')++p; return p;} size_t nextLine(size_t p)const{size_t e=lineEnd(p); return e<s.size()?e+1:e;}
    static bool isWhite(char32_t c){return c==U' '||c==U'\t';} static bool isDec(char32_t c){return c>=U'0'&&c<=U'9';} static bool isHex(char32_t c){return (c>=U'0'&&c<=U'9')||(c>=U'A'&&c<=U'F')||(c>=U'a'&&c<=U'f');} static int hexVal(char32_t c){if(c<=U'9')return c-U'0'; if(c<=U'F')return 10+c-U'A'; return 10+c-U'a';}
    static bool isAsciiLetter(char32_t c){return (c>=U'A'&&c<=U'Z')||(c>=U'a'&&c<=U'z');} static bool isWord(char32_t c){return isDec(c)||isAsciiLetter(c)||c==U'-';}
    static bool isFlowIndicator(char32_t c){return c==U','||c==U'['||c==U']'||c==U'{'||c==U'}';}
    static bool isIndicator(char32_t c){switch(c){case U'-':case U'?':case U':':case U',':case U'[':case U']':case U'{':case U'}':case U'#':case U'&':case U'*':case U'!':case U'|':case U'>':case U'\'':case U'"':case U'%':case U'@':case U'`':return true; default:return false;}}
    static bool isNsCharCP(char32_t c){return c!=0&&c!=U'\n'&&c!=U' '&&c!=U'\t'&&c!=BOM;}
    static bool isPlainSafe(Context c,char32_t ch){if(!isNsCharCP(ch))return false; if(c==FLOW_IN||c==FLOW_OUT||c==FLOW_KEY)return !isFlowIndicator(ch); return true;}
    bool isPlainFirst(Context c,size_t p)const{char32_t ch=peek(p); if(!isNsCharCP(ch))return false; if(!isIndicator(ch))return true; return (ch==U'?'||ch==U':'||ch==U'-')&&isPlainSafe(c,peek(p+1));}
    bool isPlainChar(Context c,size_t p,bool prevIsNs)const{char32_t ch=peek(p); if(isPlainSafe(c,ch)&&ch!=U':'&&ch!=U'#')return true; if(ch==U'#'&&prevIsNs)return true; if(ch==U':'&&isPlainSafe(c,peek(p+1)))return true; return false;}
    bool isUriCharAt(size_t p,size_t&len)const{char32_t c=peek(p); if(c==U'%'){if(isHex(peek(p+1))&&isHex(peek(p+2))){len=3;return true;}return false;} if(isWord(c)){len=1;return true;} switch(c){case U'#':case U';':case U'/':case U'?':case U':':case U'@':case U'&':case U'=':case U'+':case U'$':case U',':case U'_':case U'.':case U'!':case U'~':case U'*':case U'\'':case U'(':case U')':case U'[':case U']':len=1;return true;default:return false;}}
    bool isTagCharAt(size_t p,size_t&len)const{if(!isUriCharAt(p,len))return false; char32_t c=peek(p); return c!=U'!'&&!isFlowIndicator(c);} 
    bool isGlobalURI(const std::u32string&t)const{if(t.empty()||!isAsciiLetter(t[0]))return false; size_t i=1; while(i<t.size()&&(isAsciiLetter(t[i])||isDec(t[i])||t[i]==U'+'||t[i]==U'-'||t[i]==U'.'))++i; return i<t.size()&&t[i]==U':';}
    bool markerAt(size_t p,const char*m)const{if(!atLineStart(p))return false; for(int i=0;i<3;++i) if(peek(p+i)!=(unsigned char)m[i])return false; char32_t n=peek(p+3); return n==0||n==U'\n'||isWhite(n);} bool isDirectivesEndAt(size_t p)const{return markerAt(p,"---");} bool isDocumentEndAt(size_t p)const{return markerAt(p,"...");} bool isDocBoundaryAt(size_t p)const{return isDirectivesEndAt(p)||isDocumentEndAt(p);} 
    bool commentMayStart(size_t p)const{return peek(p)==U'#'&&(p==0||s[p-1]==U'\n'||isWhite(s[p-1]));} void skipInlineSpaces(size_t&p)const{while(isWhite(peek(p)))++p;} void consumeToLineBreak(size_t&p)const{while(p<s.size()&&s[p]!=U'\n')++p; if(p<s.size()&&s[p]==U'\n')++p;}
    bool consumeBlankOrCommentLine(size_t&p)const{if(!atLineStart(p))return false; size_t q=p; while(peek(q)==U' '||peek(q)==U'\t')++q; if(q>=s.size()){ if(q>p){p=q; return true;} return false;} if(peek(q)==U'\n'){p=q+1; return true;} if(peek(q)==U'#'){p=q; consumeToLineBreak(p); return true;} return false;}
    void skipBlankCommentLines(size_t&p)const{while(consumeBlankOrCommentLine(p)){} }
    bool skipSeparation(size_t&p,Context c,bool require=false)const{size_t start=p; if(c==BLOCK_KEY||c==FLOW_KEY){while(isWhite(peek(p)))++p; return !require||p>start;} bool progress=false; while(true){size_t before=p; while(isWhite(peek(p)))++p; if(p!=before)progress=true; if(commentMayStart(p)){consumeToLineBreak(p); progress=true; continue;} if(peek(p)==U'\n'){++p; progress=true; continue;} break;} return !require||progress;}
    bool lineIndentAtLeast(size_t p,int n)const{ if(p>=s.size()) return true; size_t e=lineEnd(p); bool blank=true; for(size_t i=p;i<e;++i) if(!isWhite(s[i])){blank=false;break;} if(blank) return true; int sp=0; size_t q=p; while(q<e && s[q]==U' '){++sp;++q;} return sp>=n; }
    bool skipFlowSep(size_t&p,int n,Context c)const{ size_t old=lineIndex(p); skipSeparation(p,c,false); if(lineIndex(p)!=old && p<s.size()){ if(!lineIndentAtLeast(currentLineStart(p),n)) return false; } return true; }
    bool parseBlockTrailing(size_t&p)const{skipInlineSpaces(p); if(p>=s.size())return true; if(commentMayStart(p)){consumeToLineBreak(p); skipBlankCommentLines(p); return true;} if(peek(p)==U'\n'){++p; skipBlankCommentLines(p); return true;} if(atLineStart(p)&&isDocBoundaryAt(p))return true; return false;}
    bool consumeDocumentPrefix(size_t&p){while(true){bool moved=false; while(eraseBOMAt(p))moved=true; if(consumeBlankOrCommentLine(p)){moved=true; continue;} if(!moved)break;} return true;}
    bool consumeDocumentSuffix(size_t&p){if(!isDocumentEndAt(p))return false; p+=3; skipInlineSpaces(p); if(commentMayStart(p))consumeToLineBreak(p); else if(peek(p)==U'\n')++p; else if(p<s.size())return false; skipBlankCommentLines(p); return true;}
    bool hasBadLeadingTabs()const{ for(size_t ls: lineStarts){ if(ls>=s.size()) continue; size_t e=lineEnd(ls), q=ls; bool tab=false; while(q<e && (s[q]==U' '||s[q]==U'\t')){ if(s[q]==U'\t') tab=true; ++q;} if(!tab||q>=e||s[q]==U'#') continue; char32_t t=s[q]; auto delim=[&](size_t x){return !isNsCharCP(peek(x));}; bool bad=false; if((t==U'-'||t==U'?'||t==U':') && delim(q+1)) bad=true; if(t==U'|'||t==U'>') bad=true; if(t!=U'['&&t!=U'{'&&t!=U'"'&&t!=U'\''){ for(size_t i=q;i<e;i++){ if(s[i]==U'#' && (i==q || isWhite(s[i-1]))) break; if(s[i]==U':' && (i+1==e || isWhite(s[i+1]))){ bad=true; break; } } } if(bad) return true; } return false; }
    bool parseDirectiveDocument(size_t&p){bool any=false; while(true){if(!consumeDocumentPrefix(p))return false; if(atLineStart(p)&&peek(p)==U'%'){any=true; if(!parseDirectiveLine(p))return false; continue;} break;} if(!any)return false; if(!isDirectivesEndAt(p))return false; return parseExplicitDocument(p,true);} 
    bool parseDirectiveLine(size_t&p){if(!atLineStart(p)||peek(p)!=U'%')return false; ++p; size_t nameStart=p; while(isNsCharCP(peek(p)))++p; if(p==nameStart)return false; auto name=s.substr(nameStart,p-nameStart); if(name==U("YAML")){if(!isWhite(peek(p)))return false; skipInlineSpaces(p); size_t majStart=p; if(!isDec(peek(p)))return false; while(isDec(peek(p)))++p; if(peek(p)!=U'.')return false; auto majStr=s.substr(majStart,p-majStart); ++p; if(!isDec(peek(p)))return false; while(isDec(peek(p)))++p; int major=0; for(char32_t c:majStr){major=major*10+(c-U'0'); if(major>1000)break;} if(doc.yamlDirectiveSeen)return false; doc.yamlDirectiveSeen=true; if(major>1)return false;} else if(name==U("TAG")){if(!isWhite(peek(p)))return false; skipInlineSpaces(p); std::u32string handle; if(!parseTagHandleToken(p,handle))return false; if(!isWhite(peek(p)))return false; skipInlineSpaces(p); std::u32string prefix; if(!parseTagPrefixToken(p,prefix))return false; if(doc.explicitTagHandles.count(handle))return false; doc.explicitTagHandles.insert(handle); doc.tagHandles[handle]=prefix;} else {while(isWhite(peek(p))){skipInlineSpaces(p); if(!isNsCharCP(peek(p)))break; while(isNsCharCP(peek(p)))++p;}} skipInlineSpaces(p); if(commentMayStart(p))consumeToLineBreak(p); else if(peek(p)==U'\n')++p; else if(p<s.size())return false; skipBlankCommentLines(p); return true;}
    bool parseTagHandleToken(size_t&p,std::u32string&out)const{if(peek(p)!=U'!')return false; if(peek(p+1)==U'!'){out=U("!!"); p+=2; return true;} size_t q=p+1; while(isWord(peek(q)))++q; if(q>p+1&&peek(q)==U'!'){out=s.substr(p,q-p+1); p=q+1; return true;} out=U("!"); ++p; return true;}
    bool parseTagPrefixToken(size_t&p,std::u32string&out)const{size_t start=p; if(peek(p)==U'!'){++p; while(true){size_t len=0; if(!isUriCharAt(p,len))break; p+=len;} out=s.substr(start,p-start); return true;} size_t len=0; if(!isTagCharAt(p,len))return false; p+=len; while(isUriCharAt(p,len))p+=len; out=s.substr(start,p-start); return true;}
    bool parseExplicitDocument(size_t&p,bool){if(!isDirectivesEndAt(p))return false; p+=3; return parseBlockNode(p,-1,BLOCK_IN,true,false);} bool parseBareDocument(size_t&p){return parseBlockNode(p,-1,BLOCK_IN,false,true);} bool isDelimiterAfterIndicator(size_t p)const{return !isNsCharCP(peek(p));}
    bool indentationBeforeIsSpacesOnly(size_t p)const{size_t ls=currentLineStart(p); for(size_t i=ls;i<p;++i) if(s[i]!=U' ')return false; return true;} bool sequenceIndentAllowed(int col,int parent,Context ctx)const{return ctx==BLOCK_OUT?col>=parent:col>parent;} bool mappingIndentAllowed(int col,int parent)const{return col>parent;}
    bool canStartBlockSequence(size_t p,int parent,Context ctx)const{if(peek(p)!=U'-'||!isDelimiterAfterIndicator(p+1))return false; int col=column(p); if(!sequenceIndentAllowed(col,parent,ctx))return false; if(atLineStart(p)&&!indentationBeforeIsSpacesOnly(p))return false; return true;}
    bool parseBlockNode(size_t&p,int parent,Context ctx,bool allowEmpty,bool allowInlineBlock){size_t sepStart=p; skipSeparation(p,ctx,false); bool sameLineFromStart=sameLine(sepStart,p); if(p>=s.size()||(atLineStart(p)&&isDocBoundaryAt(p)))return allowEmpty; bool seqExc=canStartBlockSequence(p,parent,ctx); if(!seqExc&&column(p)<=parent)return allowEmpty; if(allowInlineBlock){ if(canStartBlockSequence(p,parent,ctx)){int ind=column(p); return parseBlockSequence(p,ind);} if(canStartBlockMapping(p,parent)){int ind=column(p); return parseBlockMapping(p,ind);} }
        bool hasProps=false, propsSameLineContent=false; if(peek(p)==U'*'){if(!parseAlias(p))return false; return parseBlockTrailing(p);} if(peek(p)==U'!'||peek(p)==U'&'){if(!parseProperties(p,ctx))return false; hasProps=true; size_t afterProps=p; if(!skipSeparation(p,ctx,true))return parseBlockTrailing(p); propsSameLineContent=sameLine(afterProps,p); if(p>=s.size()||(atLineStart(p)&&isDocBoundaryAt(p)))return true; if(column(p)<=parent&&!canStartBlockSequence(p,parent,ctx))return true; if(peek(p)==U'*')return false;} bool allowBlockCollections=true; if(!allowInlineBlock&&sameLineFromStart&&!hasProps)allowBlockCollections=false; if(hasProps&&propsSameLineContent)allowBlockCollections=false; if(peek(p)==U'|'||peek(p)==U'>')return parseBlockScalar(p,parent); if(allowBlockCollections&&canStartBlockSequence(p,parent,ctx)){int ind=column(p); return parseBlockSequence(p,ind);} if(allowBlockCollections&&canStartBlockMapping(p,parent)){int ind=column(p); return parseBlockMapping(p,ind);} if(hasProps){if(!parseFlowContent(p,max(parent+1,0),FLOW_OUT))return false;} else {if(!parseFlowNode(p,max(parent+1,0),FLOW_OUT))return false;} return parseBlockTrailing(p);} 
    bool canStartBlockMapping(size_t p,int parent){int col=column(p); if(!mappingIndentAllowed(col,parent))return false; if(atLineStart(p)&&!indentationBeforeIsSpacesOnly(p))return false; if((peek(p)==U'?'||peek(p)==U':')&&isDelimiterAfterIndicator(p+1))return true; size_t q=p; Snapshot sn=save(); bool ok=parseImplicitKey(q,BLOCK_KEY,true); restore(sn); return ok;}
    bool parseBlockSequence(size_t&p,int entryIndent){bool first=true; while(true){size_t q=p; if(!first&&atLineStart(q)){for(int i=0;i<entryIndent;++i){if(peek(q)!=U' ')return true; ++q;}} if(column(q)!=entryIndent||peek(q)!=U'-'||!isDelimiterAfterIndicator(q+1))return first?false:true; if(atLineStart(q)&&!indentationBeforeIsSpacesOnly(q))return false; p=q+1; if(!parseBlockNode(p,entryIndent,BLOCK_IN,true,true))return false; first=false; if(p>=s.size()||(atLineStart(p)&&isDocBoundaryAt(p)))return true;}}
    bool parseBlockMapping(size_t&p,int entryIndent){bool first=true; while(true){size_t q=p; if(!first&&atLineStart(q)){for(int i=0;i<entryIndent;++i){if(peek(q)!=U' ')return true; ++q;}} if(column(q)!=entryIndent)return first?false:true; if(atLineStart(q)&&!indentationBeforeIsSpacesOnly(q))return false; if(!canStartBlockMapping(q,entryIndent-1))return first?false:true; p=q; if(!parseBlockMapEntry(p,entryIndent))return false; first=false; if(p>=s.size()||(atLineStart(p)&&isDocBoundaryAt(p)))return true;}}
    bool parseBlockMapEntry(size_t&p,int entryIndent){if(peek(p)==U'?'&&isDelimiterAfterIndicator(p+1)){++p; if(!parseBlockNode(p,entryIndent,BLOCK_OUT,true,true))return false; size_t q=p; if(atLineStart(q)){for(int i=0;i<entryIndent;++i){if(peek(q)!=U' ')return true; ++q;}} if(column(q)==entryIndent&&peek(q)==U':'&&isDelimiterAfterIndicator(q+1)){p=q+1; if(!parseBlockNode(p,entryIndent,BLOCK_OUT,true,true))return false;} return true;} if(peek(p)==U':'&&isDelimiterAfterIndicator(p+1)){++p; return parseBlockNode(p,entryIndent,BLOCK_OUT,true,false);} if(!parseImplicitKey(p,BLOCK_KEY,true))return false; if(peek(p)!=U':'||!isDelimiterAfterIndicator(p+1))return false; ++p; return parseBlockNode(p,entryIndent,BLOCK_OUT,true,false);} 
    bool parseImplicitKey(size_t&p,Context keyCtx,bool blockStyle){size_t start=p; if(peek(p)==U'['||peek(p)==U'{'||peek(p)==U'\''||peek(p)==U'"'||peek(p)==U'!'||peek(p)==U'&'){Snapshot sn=save(); size_t q=p; if(parseFlowJsonNode(q,0,keyCtx)){skipInlineSpaces(q); if(q-start<=1024&&peek(q)==U':'&&(blockStyle?isDelimiterAfterIndicator(q+1):true)){p=q; return true;}} restore(sn);} Snapshot sn=save(); size_t q=p; if(parseFlowYamlNode(q,0,keyCtx)){skipInlineSpaces(q); bool colonOK=false; if(peek(q)==U':') colonOK=blockStyle?isDelimiterAfterIndicator(q+1):!isPlainSafe(FLOW_IN,peek(q+1)); if(q-start<=1024&&colonOK){p=q; return true;}} restore(sn); return false;}
    bool parseProperties(size_t&p,Context c){bool haveTag=false,haveAnchor=false; if(peek(p)==U'!'){if(!parseTagProperty(p))return false; haveTag=true;} else if(peek(p)==U'&'){if(!parseAnchorProperty(p))return false; haveAnchor=true;} else return false; size_t q=p; if(skipSeparation(q,c,true)){if(peek(q)==U'!'||peek(q)==U'&'){if(peek(q)==U'!'){if(haveTag)return false; if(!parseTagProperty(q))return false; haveTag=true;} else {if(haveAnchor)return false; if(!parseAnchorProperty(q))return false; haveAnchor=true;} p=q;}} return true;}
    bool parseAnchorName(size_t&p,std::u32string&name)const{size_t start=p; while(isNsCharCP(peek(p))&&!isFlowIndicator(peek(p)))++p; if(p==start)return false; name=s.substr(start,p-start); return true;} bool parseAnchorProperty(size_t&p){if(peek(p)!=U'&')return false; ++p; std::u32string name; if(!parseAnchorName(p,name))return false; doc.anchors.insert(name); return true;} bool parseAlias(size_t&p){if(peek(p)!=U'*')return false; ++p; std::u32string name; if(!parseAnchorName(p,name))return false; return doc.anchors.count(name)!=0;}
    bool parseTagProperty(size_t&p){if(peek(p)!=U'!')return false; if(peek(p+1)==U'<'){p+=2; size_t start=p; while(p<s.size()&&peek(p)!=U'>'){size_t len=0; if(!isUriCharAt(p,len))return false; p+=len;} if(peek(p)!=U'>'||p==start)return false; auto tag=s.substr(start,p-start); ++p; if(tag[0]==U'!')return tag.size()>1; return isGlobalURI(tag);} std::u32string handle; if(peek(p+1)==U'!'){handle=U("!!"); p+=2;} else {size_t q=p+1; while(isWord(peek(q)))++q; if(q>p+1&&peek(q)==U'!'){handle=s.substr(p,q-p+1); p=q+1;} else {handle=U("!"); ++p;}} size_t suffixStart=p,len=0; while(isTagCharAt(p,len))p+=len; bool hasSuffix=p>suffixStart; if(!hasSuffix&&handle==U("!"))return true; if(!hasSuffix)return false; return doc.tagHandles.count(handle)!=0;}
    bool emptyTerminator(size_t p)const{char32_t ch=peek(p); return ch==0||ch==U','||ch==U']'||ch==U'}'||ch==U':';}
    bool parseFlowNode(size_t&p,int n,Context c){if(peek(p)==U'*')return parseAlias(p); if(peek(p)==U'!'||peek(p)==U'&'){if(!parseProperties(p,c))return false; size_t q=p; if(!skipSeparation(q,c,true)){p=q; return true;} if(peek(q)==U'*')return false; size_t r=q; if(parseFlowContent(r,n,c)){p=r; return true;} if(emptyTerminator(q)){p=q; return true;} return false;} return parseFlowContent(p,n,c);} 
    bool parseFlowYamlNode(size_t&p,int n,Context c){if(peek(p)==U'*')return parseAlias(p); if(peek(p)==U'!'||peek(p)==U'&'){if(!parseProperties(p,c))return false; size_t q=p; if(!skipSeparation(q,c,true)){p=q; return true;} if(peek(q)==U'*')return false; size_t r=q; if(parsePlain(r,n,c)){p=r; return true;} if(emptyTerminator(q)){p=q; return true;} return false;} return parsePlain(p,n,c);} 
    bool parseFlowJsonNode(size_t&p,int n,Context c){if(peek(p)==U'!'||peek(p)==U'&'){if(!parseProperties(p,c))return false; if(!skipSeparation(p,c,true))return false;} return parseFlowJsonContent(p,n,c);} 
    bool parseFlowContent(size_t&p,int n,Context c){if(atLineStart(p)&&isDocBoundaryAt(p))return false; if(peek(p)==U'[')return parseFlowSequence(p,n,c); if(peek(p)==U'{')return parseFlowMapping(p,n,c); if(peek(p)==U'"')return parseDoubleQuoted(p,n,c); if(peek(p)==U'\'')return parseSingleQuoted(p,n,c); return parsePlain(p,n,c);} bool parseFlowJsonContent(size_t&p,int n,Context c){if(atLineStart(p)&&isDocBoundaryAt(p))return false; if(peek(p)==U'[')return parseFlowSequence(p,n,c); if(peek(p)==U'{')return parseFlowMapping(p,n,c); if(peek(p)==U'"')return parseDoubleQuoted(p,n,c); if(peek(p)==U'\'')return parseSingleQuoted(p,n,c); return false;} Context innerFlowContext(Context c)const{return (c==BLOCK_KEY||c==FLOW_KEY)?FLOW_KEY:FLOW_IN;}
    bool parseFlowSequence(size_t&p,int n,Context c){if(peek(p)!=U'[')return false; ++p; Context ic=innerFlowContext(c); if(!skipFlowSep(p,n,ic))return false; if(atLineStart(p)&&isDocBoundaryAt(p))return false; if(peek(p)==U']'){++p; return true;} while(true){if(peek(p)==U','||peek(p)==U']'||peek(p)==0)return false; if(!parseFlowSeqEntry(p,n,ic))return false; if(!skipFlowSep(p,n,ic))return false; if(atLineStart(p)&&isDocBoundaryAt(p))return false; if(peek(p)==U','){++p; if(!skipFlowSep(p,n,ic))return false; if(atLineStart(p)&&isDocBoundaryAt(p))return false; if(peek(p)==U']'){++p; return true;} continue;} if(peek(p)==U']'){++p; return true;} return false;}}
    bool parseFlowMapping(size_t&p,int n,Context c){if(peek(p)!=U'{')return false; ++p; Context ic=innerFlowContext(c); if(!skipFlowSep(p,n,ic))return false; if(atLineStart(p)&&isDocBoundaryAt(p))return false; if(peek(p)==U'}'){++p; return true;} while(true){if(peek(p)==U','||peek(p)==U'}'||peek(p)==0)return false; if(!parseFlowMapEntry(p,n,ic))return false; if(!skipFlowSep(p,n,ic))return false; if(atLineStart(p)&&isDocBoundaryAt(p))return false; if(peek(p)==U','){++p; if(!skipFlowSep(p,n,ic))return false; if(atLineStart(p)&&isDocBoundaryAt(p))return false; if(peek(p)==U'}'){++p; return true;} continue;} if(peek(p)==U'}'){++p; return true;} return false;}}
    bool parseFlowSeqEntry(size_t&p,int n,Context c){Snapshot sn=save(); size_t q=p; if(parseFlowPair(q,n,c)){p=q; return true;} restore(sn); return parseFlowNode(p,n,c);} 
    bool parseFlowPair(size_t&p,int n,Context c){if(peek(p)==U'?'&&isDelimiterAfterIndicator(p+1)){++p; if(!skipFlowSep(p,n,c))return false; if(peek(p)==U','||peek(p)==U']'||peek(p)==U'}')return true; return parseFlowMapImplicitEntry(p,n,c,true);} return parseFlowPairEntry(p,n,c);} 
    bool parseFlowPairEntry(size_t&p,int n,Context c){if(peek(p)==U':'&&!isPlainSafe(c,peek(p+1))){++p; return parseFlowValueAfterColonAlreadyConsumed(p,n,c,false);} size_t start=p; Snapshot sn=save(); size_t q=p; if(parseFlowJsonNode(q,0,FLOW_KEY)){skipInlineSpaces(q); if(q-start<=1024&&peek(q)==U':'){p=q+1; return parseFlowValueAfterColonAlreadyConsumed(p,n,c,true);}} restore(sn); sn=save(); q=p; if(parseFlowYamlNode(q,0,FLOW_KEY)){skipInlineSpaces(q); if(q-start<=1024&&peek(q)==U':'&&!isPlainSafe(c,peek(q+1))){p=q+1; return parseFlowValueAfterColonAlreadyConsumed(p,n,c,false);}} restore(sn); return false;}
    bool parseFlowMapEntry(size_t&p,int n,Context c){if(peek(p)==U'?'&&isDelimiterAfterIndicator(p+1)){++p; if(!skipFlowSep(p,n,c))return false; if(peek(p)==U','||peek(p)==U'}')return true; return parseFlowMapImplicitEntry(p,n,c,true);} return parseFlowMapImplicitEntry(p,n,c,false);} 
    bool parseFlowMapImplicitEntry(size_t&p,int n,Context c,bool allowNoColon){(void)allowNoColon; if(peek(p)==U':'&&!isPlainSafe(c,peek(p+1))){++p; return parseFlowValueAfterColonAlreadyConsumed(p,n,c,false);} Snapshot sn=save(); size_t q=p; if(parseFlowJsonNode(q,n,c)){if(!skipFlowSep(q,n,c)){restore(sn); return false;} if(peek(q)==U':'){p=q+1; return parseFlowValueAfterColonAlreadyConsumed(p,n,c,true);} p=q; return true;} restore(sn); sn=save(); q=p; if(parseFlowYamlNode(q,n,c)){if(!skipFlowSep(q,n,c)){restore(sn); return false;} if(peek(q)==U':'&&!isPlainSafe(c,peek(q+1))){p=q+1; return parseFlowValueAfterColonAlreadyConsumed(p,n,c,false);} p=q; return true;} restore(sn); return false;}
    bool parseFlowValueAfterColonAlreadyConsumed(size_t&p,int n,Context c,bool adjacent){if(!adjacent&&isPlainSafe(c,peek(p)))return false; if(!skipFlowSep(p,n,c))return false; if(atLineStart(p)&&isDocBoundaryAt(p))return false; char32_t ch=peek(p); if(ch==U','||ch==U'}'||ch==U']'||ch==0)return true; return parseFlowNode(p,n,c);} 
    bool parseDoubleQuoted(size_t&p,int n,Context c){if(peek(p)!=U'"')return false; ++p; while(p<s.size()){if((c==BLOCK_KEY||c==FLOW_KEY)&&peek(p)==U'\n')return false; if(atLineStart(p)&&isDocBoundaryAt(p))return false; char32_t ch=peek(p); if(ch==U'"'){++p; return true;} if(ch==U'\\'){++p; char32_t e=peek(p); if(e==U'\n'){++p; if(!lineIndentAtLeast(p,n))return false; continue;} if(e==0)return false; switch(e){case U'0':case U'a':case U'b':case U't':case U'\t':case U'n':case U'v':case U'f':case U'r':case U'e':case U' ':case U'"':case U'/':case U'\\':case U'N':case U'_':case U'L':case U'P':++p; continue; case U'x':case U'u':case U'U':{int cnt=(e==U'x')?2:(e==U'u'?4:8); ++p; uint32_t val=0; for(int i=0;i<cnt;++i){if(!isHex(peek(p)))return false; val=(val<<4)|hexVal(peek(p)); ++p;} if(val>0x10FFFF||(val>=0xD800&&val<=0xDFFF))return false; continue;} default:return false;}} if(ch==U'\n'){++p; if(!lineIndentAtLeast(p,n))return false; continue;} if(ch==0)return false; ++p;} return false;}
    bool parseSingleQuoted(size_t&p,int n,Context c){if(peek(p)!=U'\'')return false; ++p; while(p<s.size()){if((c==BLOCK_KEY||c==FLOW_KEY)&&peek(p)==U'\n')return false; if(atLineStart(p)&&isDocBoundaryAt(p))return false; char32_t ch=peek(p); if(ch==U'\''){if(peek(p+1)==U'\''){p+=2; continue;} ++p; return true;} if(ch==U'\n'){++p; if(!lineIndentAtLeast(p,n))return false; continue;} if(ch==0)return false; ++p;} return false;}
    bool parsePlain(size_t&p,int n,Context c){if(!isPlainFirst(c,p))return false; bool prevIsNs=false; while(true){bool consumedNonSpaceOnLine=false; while(p<s.size()){char32_t ch=peek(p); if(ch==U'\n')break; if((c==FLOW_IN||c==FLOW_OUT||c==FLOW_KEY)&&isFlowIndicator(ch))break; if(ch==U'#'&&(p>0&&isWhite(s[p-1])))break; if(ch==U':'&&!isPlainSafe(c,peek(p+1)))break; if(isWhite(ch)){++p; prevIsNs=false; continue;} if(!isPlainChar(c,p,prevIsNs))return consumedNonSpaceOnLine; ++p; prevIsNs=true; consumedNonSpaceOnLine=true;} if(c==BLOCK_KEY||c==FLOW_KEY)return true; if(peek(p)!=U'\n')return true; size_t q=p+1; while(true){size_t ls=q; if(ls>=s.size())return true; if(atLineStart(ls)&&isDocBoundaryAt(ls))return true; size_t e=lineEnd(ls); bool blank=true; for(size_t i=ls;i<e;++i) if(!isWhite(s[i])){blank=false; break;} if(blank){if(e<s.size())q=e+1; else return true;} else break;} int spaces=0; while(peek(q)==U' '){++q;++spaces;} if(spaces<n)return true; while(peek(q)==U'\t'||peek(q)==U' ')++q; if(q>=s.size()||peek(q)==U'\n')return true; if(atLineStart(q)&&isDocBoundaryAt(q))return true; if(!isPlainChar(c,q,false))return true; p=q; prevIsNs=false;}}
    bool parseBlockScalar(size_t&p,int parent){char32_t style=peek(p); if(style!=U'|'&&style!=U'>')return false; ++p; int indentIndicator=-1; bool haveChomp=false; while(true){char32_t ch=peek(p); if(ch>=U'1'&&ch<=U'9'){if(indentIndicator!=-1)return false; indentIndicator=ch-U'0'; ++p;} else if(ch==U'0')return false; else if(ch==U'+'||ch==U'-'){if(haveChomp)return false; haveChomp=true; ++p;} else break;} skipInlineSpaces(p); if(commentMayStart(p))consumeToLineBreak(p); else if(peek(p)==U'\n')++p; else if(p<s.size())return false; int contentIndent; if(indentIndicator!=-1)contentIndent=max(0,parent+indentIndicator); else {size_t q=p; int maxLeadingBlank=0; bool found=false; int firstIndent=0; while(q<s.size()){if(atLineStart(q)&&isDocBoundaryAt(q))break; size_t e=lineEnd(q); int sp=0; size_t r=q; while(r<e&&s[r]==U' '){++r;++sp;} bool onlySpaces=true; for(size_t i=r;i<e;++i)if(s[i]!=U' '){onlySpaces=false;break;} if(onlySpaces){maxLeadingBlank=max(maxLeadingBlank,sp); q=(e<s.size()?e+1:e); continue;} if(sp<=parent)break; found=true; firstIndent=sp; break;} if(found){if(maxLeadingBlank>firstIndent)return false; contentIndent=firstIndent;} else {contentIndent=max(parent+1,maxLeadingBlank); if(contentIndent<0)contentIndent=0;}} size_t q=p; while(q<s.size()){if(atLineStart(q)&&isDocBoundaryAt(q))break; size_t e=lineEnd(q); int sp=0; size_t r=q; while(r<e&&s[r]==U' '){++r;++sp;} bool onlySpaces=true; for(size_t i=r;i<e;++i)if(s[i]!=U' '){onlySpaces=false;break;} if(onlySpaces){q=(e<s.size()?e+1:e); continue;} for(size_t i=q;i<e;++i)if(s[i]==BOM)return false; if(sp>=contentIndent){q=(e<s.size()?e+1:e); continue;} if(r<e&&s[r]==U'#'){q=(e<s.size()?e+1:e); skipBlankCommentLines(q); break;} if(sp>parent)return false; break;} p=q; return true;}
};

static bool isPrintableCP(uint32_t cp){return cp==0x09||cp==0x0A||cp==0x0D||(cp>=0x20&&cp<=0x7E)||cp==0x85||(cp>=0xA0&&cp<=0xD7FF)||(cp>=0xE000&&cp<=0xFFFD)||(cp>=0x10000&&cp<=0x10FFFF);} 
static bool decodeUTF8(const string&b,vector<uint32_t>&out){size_t i=0,n=b.size(); while(i<n){unsigned char c=b[i]; uint32_t cp=0; int len=0; if(c<=0x7F){cp=c;len=1;} else if(c>=0xC2&&c<=0xDF){cp=c&0x1F;len=2;} else if(c>=0xE0&&c<=0xEF){cp=c&0x0F;len=3;} else if(c>=0xF0&&c<=0xF4){cp=c&0x07;len=4;} else return false; if(i+len>n)return false; for(int j=1;j<len;++j){unsigned char d=b[i+j]; if((d&0xC0)!=0x80)return false; cp=(cp<<6)|(d&0x3F);} if((len==3&&cp<0x800)||(len==4&&cp<0x10000))return false; if(cp>0x10FFFF||(cp>=0xD800&&cp<=0xDFFF))return false; out.push_back(cp); i+=len;} return true;}
static bool decodeUTF16(const string&b,bool be,vector<uint32_t>&out){if(b.size()%2)return false; auto unit=[&](size_t i){unsigned char a=b[i],c=b[i+1]; return (uint16_t)(be?((a<<8)|c):((c<<8)|a));}; for(size_t i=0;i<b.size();){uint16_t u=unit(i); i+=2; if(u>=0xD800&&u<=0xDBFF){if(i>=b.size())return false; uint16_t v=unit(i); i+=2; if(v<0xDC00||v>0xDFFF)return false; out.push_back(0x10000+(((uint32_t)u-0xD800)<<10)+((uint32_t)v-0xDC00));} else if(u>=0xDC00&&u<=0xDFFF)return false; else out.push_back(u);} return true;}
static bool decodeUTF32(const string&b,bool be,vector<uint32_t>&out){if(b.size()%4)return false; for(size_t i=0;i<b.size();i+=4){unsigned char b0=b[i],b1=b[i+1],b2=b[i+2],b3=b[i+3]; uint32_t cp=be?(((uint32_t)b0<<24)|((uint32_t)b1<<16)|((uint32_t)b2<<8)|b3):(((uint32_t)b3<<24)|((uint32_t)b2<<16)|((uint32_t)b1<<8)|b0); if(cp>0x10FFFF||(cp>=0xD800&&cp<=0xDFFF))return false; out.push_back(cp);} return true;}
static bool decodeInput(const string&bytes,std::u32string&out){enum Enc{UTF8,UTF16BE,UTF16LE,UTF32BE,UTF32LE}enc=UTF8; size_t n=bytes.size(); auto B=[&](size_t i){return i<n?(unsigned char)bytes[i]:0;}; if(n>=4&&B(0)==0x00&&B(1)==0x00&&B(2)==0xFE&&B(3)==0xFF)enc=UTF32BE; else if(n>=4&&B(0)==0x00&&B(1)==0x00&&B(2)==0x00)enc=UTF32BE; else if(n>=4&&B(0)==0xFF&&B(1)==0xFE&&B(2)==0x00&&B(3)==0x00)enc=UTF32LE; else if(n>=4&&B(1)==0x00&&B(2)==0x00&&B(3)==0x00)enc=UTF32LE; else if(n>=2&&B(0)==0xFE&&B(1)==0xFF)enc=UTF16BE; else if(n>=2&&B(0)==0x00)enc=UTF16BE; else if(n>=2&&B(0)==0xFF&&B(1)==0xFE)enc=UTF16LE; else if(n>=2&&B(1)==0x00)enc=UTF16LE; vector<uint32_t> cps; bool ok=false; if(enc==UTF8)ok=decodeUTF8(bytes,cps); else if(enc==UTF16BE)ok=decodeUTF16(bytes,true,cps); else if(enc==UTF16LE)ok=decodeUTF16(bytes,false,cps); else if(enc==UTF32BE)ok=decodeUTF32(bytes,true,cps); else ok=decodeUTF32(bytes,false,cps); if(!ok)return false; for(size_t i=0;i<cps.size();++i){uint32_t cp=cps[i]; if(!isPrintableCP(cp))return false; if(cp==0x0D){if(i+1<cps.size()&&cps[i+1]==0x0A)++i; out.push_back(U'\n');} else if(cp==0x0A)out.push_back(U'\n'); else out.push_back((char32_t)cp);} return true;}
int main(){ios::sync_with_stdio(false); cin.tie(nullptr); string bytes((istreambuf_iterator<char>(cin)),{}); std::u32string data; bool ok=decodeInput(bytes,data); if(ok){Parser p(std::move(data)); ok=p.parseStream();} cout<<(ok?"valid":"invalid"); return 0;}
